# SPDX-License-Identifier: CC0-1.0
# SPDX-FileCopyrightText: 2023 Collabora, Ltd.

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  CLANG_VERSION: "15"
  CLANG_TIDY: "clang-tidy-$CLANG_VERSION"
  CLANG_FORMAT: "clang-format-$CLANG_VERSION"

stages:
  - build
  - analyze
  - release

build-ubuntu-2204:
  image: registry.freedesktop.org/mateosss/basalt/ubuntu/22.04
  stage: build
  when: manual
  script:
    - echo BUILD_UBUNTU_2204_JOB_ID=$CI_JOB_ID >> release.env
    - cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Release -DBASALT_BUILD_SHARED_LIBRARY_ONLY=on -DCMAKE_CXX_FLAGS="-mtune=haswell -march=haswell" -DCMAKE_C_FLAGS="-mtune=haswell -march=haswell"
    - time cmake --build build
    - cd build && cpack
    - mv *.deb ../basalt-monado-ubuntu-22.04-haswell-amd64.deb
  artifacts:
    name: basalt-monado-ubuntu-22.04-haswell-amd64
    expose_as: "basalt-monado-ubuntu-2204-haswell-amd64-deb"
    paths:
      - "basalt-monado-ubuntu-22.04-haswell-amd64.deb"
    reports:
      dotenv: release.env

clang-tidy:
  stage: analyze
  image: registry.freedesktop.org/mateosss/basalt/ubuntu/22.04
  when: manual
  script:
    - apt-get update && apt-get install -y $CLANG_TIDY
    - $CLANG_TIDY --version
    - cmake -B build
    - echo $CI_DEFAULT_BRANCH
    - git diff $CI_DEFAULT_BRANCH
    - |-
      if git diff main..HEAD --name-only --exit-code; then # If on the main branch, analyze all files
        ./scripts/clang-tidy-all.sh || true
      else # # Otherwise analyze only changed files that were not deleted
        git diff --name-only --diff-filter=d $CI_DEFAULT_BRANCH...HEAD | grep -E '\.cpp|\.hpp|\.h$' | xargs $CLANG_TIDY --config-file=.clang-tidy -p build || true
      fi
    - echo Done

clang-format:
  stage: analyze
  image: registry.freedesktop.org/mateosss/basalt/ubuntu/22.04
  when: manual
  script:
    - apt-get update && apt-get install -y $CLANG_FORMAT
    - $CLANG_FORMAT --version
    - ./scripts/clang-format-all.sh
    - git diff --exit-code

release:
  stage: release
  image: registry.freedesktop.org/mateosss/basalt/ubuntu/22.04
  when: manual
  script:
    - echo "Releasing artifacts of previous jobs"
    - curl --location --output /usr/local/bin/release-cli "https://gitlab.com/api/v4/projects/gitlab-org%2Frelease-cli/packages/generic/release-cli/latest/release-cli-linux-amd64"
    - chmod +x /usr/local/bin/release-cli
  needs: ["build-ubuntu-2204"]
  release:
    name: "Release of $CI_COMMIT_SHORT_SHA"
    tag_name: "release-$CI_COMMIT_SHORT_SHA"
    description: "Release of Monado's Basalt for $CI_COMMIT_SHORT_SHA"
    assets:
      links:
        - name: "Ubuntu 22.04 .deb (amd64, -march=haswell)"
          url: "https://gitlab.freedesktop.org/mateosss/basalt/-/jobs/${BUILD_UBUNTU_2204_JOB_ID}/artifacts/raw/basalt-monado-ubuntu-22.04-haswell-amd64.deb"
          link_type: package
